# Generated by Django 4.2.15 on 2024-09-03 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backenduser',
            old_name='categories',
            new_name='subscribed_categories',
        ),
    ]
